name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test Unix
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: 'tag-exists-action: true'
        id: checkTag
        uses: ./
        with: 
          tag: 'v1.0.0'
      - name: 'tag-exists-action: false'
        id: notExist
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
      - name: 'tag-exists-action: external repo - true'
        id: externalRepoTagExists
        uses: ./
        with: 
          tag: 'v3.6.0'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo - false'
        id: externalRepoTagNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo exists - false'
        id: externalRepoNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'fakeRepo/fakerepo'

      - name: Result of checkTag
        if: always()
        run: test "true" = "${{ steps.checkTag.outputs.exists }}"
      - name: Result of notExist
        if: always()
        run: test "false" = "${{ steps.notExist.outputs.notExist }}"
      - name: Result of externalRepoTagExists
        if: always()
        run: test "true" = "${{ steps.checkTag.outputs.externalRepoTagExists }}"
      - name: Result of externalRepoTagNotExists
        if: always()
        run: test "true" = "${{ steps.checkTag.outputs.externalRepoTagNotExists }}"
      - name: Result of externalRepoNotExists
        if: always()
        run: test "true" = "${{ steps.checkTag.outputs.externalRepoNotExists }}"
