name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test-unix:
    name: Test Unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'tag-exists-action: true'
        id: checkTag
        uses: ./
        with: 
          tag: 'v1.0.0'
      - name: 'tag-exists-action: false'
        id: notExist
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
      - name: 'tag-exists-action: external repo - true'
        id: externalRepoTagExists
        uses: ./
        with: 
          tag: 'v3.6.0'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo - false'
        id: externalRepoTagNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo exists - false'
        id: externalRepoNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'fakeRepo/fakerepo'

      - name: Result of checkTag
        run: test "true" = "${{ steps.checkTag.outputs.exists }}"
      - name: Result of notExist
        run: test "false" = "${{ steps.notExist.outputs.exists }}"

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'tag-exists-action: true'
        id: checkTag
        uses: ./
        with: 
          tag: 'v1.0.0'
      - name: 'tag-exists-action: false'
        id: notExist
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
      - name: 'tag-exists-action: external repo - true'
        id: externalRepoTagExists
        uses: ./
        with: 
          tag: 'v3.6.0'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo - false'
        id: externalRepoTagNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo exists - false'
        id: externalRepoNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'fakeRepo/fakerepo'
          
      - name: Result of checkTag
        run: test "true" = "${{ steps.checkTag.outputs.exists }}"
      - name: Result of notExist
        run: test "false" = "${{ steps.notExist.outputs.exists }}"

  test-macos:
    name: Test MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'tag-exists-action: true'
        id: checkTag
        uses: ./
        with: 
          tag: 'v1.0.0'
      - name: 'tag-exists-action: false'
        id: notExist
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
      - name: 'tag-exists-action: external repo - true'
        id: externalRepoTagExists
        uses: ./
        with: 
          tag: 'v3.6.0'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo - false'
        id: externalRepoTagNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'actions/checkout'
      - name: 'tag-exists-action: external repo exists - false'
        id: externalRepoNotExists
        uses: ./
        with: 
          tag: 'not-exist-tag-for-testing'
          repo: 'fakeRepo/fakerepo'

      - name: Result of checkTag
        run: test "true" = "${{ steps.checkTag.outputs.exists }}"
      - name: Result of notExist
        run: test "false" = "${{ steps.notExist.outputs.exists }}"
